### ISSUE TITLE
NoSuchFileException

### ISSUE THREAD

**Issue by eEQK** [RuneStar/launcher#1]
# Expected Behavior

Game launches properly

# Current Behavior

Launcher throws an exception without opening the game

# Failure Information

## Steps to Reproduce

1. Download the [current release](https://github.com/RuneStar/launcher/releases/tag/0.1.0-SNAPSHOT-8)
2. Run it

## Context

* System info: ![](https://i.imgur.com/Ohgcch9.png)
* Confirmed to fail on Oracle JDK 8, OpenJDK 8 and OpenJDK 11

## Failure Logs

![](https://i.imgur.com/oH4EFfp.png)

**Comment by hunterwb** [comment]
Should be fixed in the new release https://github.com/RuneStar/launcher/releases/tag/0.1.0-SNAPSHOT-9
